version: '3'
services:
  keycloak:

    image: antiope
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin 
      KEYCLOAK_ADMIN_PASSWORD: admin
      ANTIOPE_CONFIG: Wwp7ICJyZWFsbU5hbWUiOiAicmVhbG0xIiwKICAiYnJva2VySXAiOiAia2Fma2EiLAogICJicm9rZXJQb3J0IjogIjkwOTIiLAogICJ0b3BpYyI6ICJ0b3BpYzEiCn0sCnsgInJlYWxtTmFtZSI6ICJyZWFsbTIiLAogICJicm9rZXJJcCI6ICJrYWZrYSIsCiAgImJyb2tlclBvcnQiOiAiOTA5MiIsCiAgInRvcGljIjogInRvcGljMiIgICAKfQpd
    command: start-dev
    
  zookeeper:
    restart: always
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    environment:    
      - ALLOW_ANONYMOUS_LOGIN=yes
    depends_on:
      - kafka
      

  kafka:
    image: 'confluentinc/cp-kafka:7.2.6'
    container_name: kafka
    ports:
      - '9092:9092'
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS=5000

    depends_on:
      zookeeper:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "sh", "-c", "nc -z -v -w5 localhost 9092" ]
      interval: 5s
      timeout: 5s
      retries: 5
