version: '3'
services:
  keycloak:
    depends_on:
      - kafka
    image: keycloak-kafka
    build: .
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin 
      KEYCLOAK_ADMIN_PASSWORD: admin
      KAFKA_TOPIC: keycloak-events
      KAFKA_ADMIN_TOPIC: keycloak-admin-events
      KAFKA_CLIENT_ID: keycloak
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      KAFKA_VALUE_SERIALIZER_CLASS: io.confluent.kafka.serializers.KafkaAvroSerializer
      AUTO_REGISTER_SCHEMAS: 'true'
    command: start-dev
    
  zookeeper:
    restart: always
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    environment:    
      - ALLOW_ANONYMOUS_LOGIN=yes
      
  kafka:
    depends_on:
      - zookeeper
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      KAFKA_CFG_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://kafka:9094
      KAFKA_CFG_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "keycloak-events:1:1"
      ALLOW_PLAINTEXT_LISTENER: "yes"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  schema-registry:
    image: confluentinc/cp-schema-registry:7.3.3
    restart: always
    depends_on:
      - kafka
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'kafka:9092'
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
    deploy:
      resources:
        limits:
          memory: 512MB

  redpanda-console:
    image: docker.redpanda.com/vectorized/console:latest
    restart: always
    depends_on:
      - kafka
    ports:
      - "9000:8080"
    environment:
      SERVER_BASEPATH: /redpanda
      #METRICSNAMESPACE: redpanda-console
      KAFKA_BROKERS: ${KAFKA_BROKERS:-kafka:9092}
      KAFKA_SCHEMAREGISTRY_ENABLED: "true"
      KAFKA_SCHEMAREGISTRY_URLS: "http://schema-registry:8081"
      CONNECT_ENABLED: "false"
      CONNECT_CLUSTERS_NAME: connect-cluster
      CONNECT_CLUSTERS_URL: "http://connect:8083"
    deploy:
      resources:
        limits:
          memory: 1G

networks:
  default:
    name: keycloak-kafka-network